const path = require('path');
const writeupFolder = '/files/writeups/';

// TODO: Remove hardcoded file list.
// Instead, search through /files/writeups for writeup files.
// Most of the fields can be automatically generated by the file path
exports.writeups = [
    {
        title: 'Vases',
        url: '/aio/2019/vases/',
        relurl: 'aio/2019/vases/',
        dir: '/AIO/2019/Vases/',
    },
    {
        title: 'Addition',
        url: '/orac/starter-problems-1/addition/',
        relurl: 'orac/starter-problems-1/addition/',
        dir: '/Orac/Starter Problems 1/Addition/',
    },
    {
        title: 'Sitting or Standing',
        url: '/orac/starter-problems-1/sitting-or-standing/',
        relurl: 'orac/starter-problems-1/sitting-or-standing/',
        dir: '/Orac/Starter Problems 1/Sitting or Standing/',
    },
];

exports.index = function (req, res) {
    res.render('writeup_list.pug', {
        writeups: exports.writeups,
    });
}

exports.renderer = new Object();
exports.writeups.forEach(writeup => {
    exports.renderer[writeup.url] = function (req, res) {
        res.render('writeup.pug', {
            title: writeup.title,
            problemFile:  path.join(writeupFolder, writeup.dir, 'problem.html'),
            analysisFile: path.join(writeupFolder, writeup.dir, 'analysis.html'),
        });
    }
});
